name: First Workflow
on: workflow_dispatch #Manual trigger for the workflow. The user manually starts the workflow.
                      #Most populars triggers are:
                      #push, pull_request, create, fork, issues, issue_comment, watch, discussion & many more.
                      #Others can be:
                      #workflow_dispatch, repository_dispatch, schedule & workflow_call.
                      #GitHub Actions events available: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
jobs:
  first-job:
    runs-on: ubuntu-latest #The runner image I want to use for my GitHub Actions workflow.
    steps:
      - name: Print greeting #Name of the first step
        run: | #The pipe symbol allows to execute multi-line commands
            echo "Hello World!"
            echo "Hello to my first GitHub Action!"
      - name: Print goodbye
        run: echo "Done - bye!"
  #Add a new job in my workflow
  second-job:
    needs: first-job #When the "first-job" finishes, it starts the "second-job"
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting II
        run:
            echo "This is my second job via GitHub Actions!"
      - name: Print greeting III
        run:
            echo "This is a second step in my seconds job!"
  #By default, multiple jobs runs in parallel. There 2 types of running: parallel or sequential.